@PORT=3000

POST http://localhost:{{PORT}}/register
content-type: application/json

{
    "username": "uname1",
    "password": "pw"
}

###
POST http://localhost:{{PORT}}/customer/login
content-type: application/json

{
    "username": "uname1",
    "password": "pw"
}

###
PUT http://localhost:{{PORT}}/customer/auth/review/2?review=this is a second review1S

###
DELETE http://localhost:{{PORT}}/customer/auth/review/2

###
GET http://localhost:{{PORT}}

