@PORT=5000

POST http://localhost:{{PORT}}/register
content-type: application/json

{
    "username": "uname",
    "password": "pw"
}

###
POST http://localhost:{{PORT}}/customer/login
content-type: application/json

{
    "username": "uname",
    "password": "pw"
}